services:
  - type: web
    name: video-retriever
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py --host 0.0.0.0 --port $PORT --no-debug
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: false
